trigger:
- refs/heads/*
- refs/pull/*/merge
- refs/tags/*

strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-20.04'
    macOS:
      imageName: 'macos-11'
    Windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- bash: |
    node scripts/bootstrap.js --target-cpu=x64
    node scripts/build.js out/Release
  displayName: Build

- script: node scripts/create_dist.js
  displayName: Create distribution

- script: node scripts/test.js
  displayName: Run tests

- bash: |
    BRANCH=$(Build.SourceBranch)
    TAG=${BRANCH:10}
    echo "##vso[task.setvariable variable=Name;isOutput=true]$TAG"
  displayName: Get Tag Name
  name: Tag
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

- task: GithubRelease@0
  displayName: Create GitHub Release
  condition: and(succeeded(), startsWith(variables['Tag.Name'], 'v'))
  inputs:
    gitHubConnection: GitHub Yue
    repositoryName: yue/build-gn
    action: Edit
    tagSource: auto
    tag: $(Tag.Name)
    title: GN $(Tag.name)
    releaseNotesSource: input
    releaseNotes: (placeholder)
    assets: 'out/Release/*.zip'
    assetUploadMode: replace
    isDraft: true
    addChangelog: false
