trigger:
- refs/heads/*
- refs/pull/*/merge
- refs/tags/*

jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
  steps:
  - template: azure-pipelines-template.yml

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.15'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
  steps:
  - template: azure-pipelines-template.yml

- job: linux_build
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
  steps:
  - template: azure-pipelines-template.yml
