name: build-gn

on: push

jobs:
  build:
    runs-on: >-
      ${{
        (matrix.os == 'mac' && matrix.arch == 'arm64') &&
          'macos-15' ||
          (fromJson('{"linux":"ubuntu-22.04","mac":"macos-13","win":"windows-2022"}')[matrix.os])
      }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [linux, mac, win]
        arch: [x64]
        include:
          - os: linux
            arch: arm64
          - os: mac
            arch: arm64

    steps:
      - name: Install Linux Arm Toolchains
        if: runner.os == 'linux' && matrix.arch == 'arm64'
        run: sudo apt install -y binutils-aarch64-linux-gnu

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-${{ matrix.os }}-${{ matrix.arch }}

      - name: Build
        run: |
          node scripts/bootstrap.js --target-cpu=${{ matrix.arch }} --cc-wrapper=ccache
          node scripts/build.js out/Release

      - name: Create distribution
        run: node scripts/create_dist.js

      - name: Run tests
        if: runner.arch == matrix.arch
        run: node scripts/test.js

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: gn-${{ matrix.os }}-${{ matrix.arch }}
          path: out/Release/gn_*.zip
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      # Needed by action-gh-release.
      contents: write

    steps:
      - name: Download Files
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: build-gn ${{ github.ref_name }}
          body: '## Changelog'
          files: '*.zip'
